# this book gathers facts about all instances filtered by tag name
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - include_vars: "ec-vars.yml"
  - name: "facts"
    ec2_instance_facts:
      filters:
        "tag:Name": "{{ ec_filters_tag_name }}"
        #"tag:Role": "{{ ec_filters_tag_role }}"
  # place ec2_instance_facts into a variable
    register: instances

  # https://blog.crisp.se/2016/10/20/maxwenzin/how-to-append-to-lists-in-ansible
  - name: init aws instance ids list
    set_fact:
      ids: []

  # dump number of instances
  - debug:
      msg: "{{ instances.instances|length }}"

  # collect instance_ids to ids[] list
  - with_items: " {{instances.instances}} "
    set_fact:
      ids: "{{ ids }} + [ '{{ item.instance_id }}' ]"

  # dump instance_ids
  - debug:
      msg: "{{ ids }}"

#  - with_items: " {{instances.instances}} "
#    debug:
#      msg: "{{ item }}"

#  # dump variable
#  - debug:
#      var: instances
#
#  # dump nested variable
#  - debug:
#      msg: "{{ instances.instances }}"

#  # iterate over items:
#  - with_items: " {{instances.instances}} "
#    debug:
#      msg: "{{ item }}"
